# .devcontainer/Dockerfile
FROM mcr.microsoft.com/devcontainers/javascript-node:0-18-bullseye

# [Optional] Uncomment this section to install additional OS packages.
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install --no-install-recommends <your-package-list-here>

# [Optional] Uncomment if you want to install Python and related tools
# ENV PYTHONDONTWRITEBYTECODE 1
# ENV PYTHONUNBUFFERED 1
# RUN apt-get update && export DEBIAN_FRONTEND=noninteractive \
#     && apt-get -y install python3-pip
# RUN pip3 install --upgrade pip